### ISSUE TITLE
How to set title when history change?

### ISSUE THREAD

**Issue by jas-chen** [router5/router5-history#2]
Hi,

Is there any recommend way to do this? Thanks!

**Comment by troch** [comment]
Hi @jas-chen, sorry I have missed the notification when you posted your issue.

I am not supported this, I will think of a way to do so.

**Comment by jas-chen** [comment]
@troch this is how I did that:

```javascript
var routeConfig = [
  {
    name: 'home',
    path: '/',
    title: 'Home Page'
  },
  {
    name: 'about',
    path: '/about/',
    title: 'About Page'
  }
];

function titleMiddleware(toRouteState, fromRouteState, done) {
    routeConfig.forEach((route) => {
      if (route.name === toRouteState.name) {
        document.title = route.title;
      }
    });

    done();
  }

new Router5(routeConfig)
  .useMiddleware(titleMiddleware)
  .start();
```

It works well :+1:

**Comment by troch** [comment]
oh right, you are talking about `document.title`, not `history.state.title`?

`history.state.title` is not well supported by browsers.
`document.title` I recommend, and the way you are using it is good. You can also use a plugin and update your title using `onTransitionSuccess` (and `onTransitionError` if you need to).

**Comment by jas-chen** [comment]
Ok, I'll try it out, thanks!
