### ISSUE TITLE
encodeURIComponent where necessary

### ISSUE THREAD

**Issue by teohhanhui** [router5/router5-history#3]
e.g. query params

**Comment by troch** [comment]
@teohhanhui I will fix that in [path-parser](https://github.com/troch/path-parser).

**Comment by troch** [comment]
Fixed and released with router5@1.1.1

**Comment by troch** [comment]
@teohhanhui is that you who raised an issue somewhere about a route callback invoked twice on start? Can't find it anymore.

**Comment by teohhanhui** [comment]
@troch I don't think that's an actual issue. It was my own code that was at fault.

**Comment by troch** [comment]
@teohhanhui no twas an issue, listeners registered prior to the router starting were invoked twice when defaulting to the default route. I has now be fixed in 1.2.1.

**Comment by teohhanhui** [comment]
Mine was a different problem :)

**Comment by troch** [comment]
OK :)
