### ISSUE TITLE
Knowing if a transition is due to popstate (back/forward)

### ISSUE THREAD

**Issue by dogoku** [router5/router5-history#5]
Hi there, I'm using router5 to build a SPA and so far things have been a breeze to setup.

I was wondering though, if there's a way for the history plugin to inform other components (middleware/plugins/listeners) that a transition is happening due to a popstate event (back/forward), e.g by adding something to the transition meta-data

Thanks

**Comment by troch** [comment]
It is not supported, but I don't see why it should not be. I'll support it in a near future (I'll include it to v4, which is almost ready to go).

**Comment by troch** [comment]
v4 took a bit longer, but now in `meta` property of states, you'll find a `source` property set to `popstate` if navigation has been caused by history popping.
